language: node_js
node_js:
- 6
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- yarn install
scripts:
- yarn test
- yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_dc4cacc08359_key -iv $encrypted_dc4cacc08359_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "yushen7"
- git config --global user.email "431185521@qq.com"
