language: node_js
node_js:
- 6
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- yarn install
scripts:
- yarn test
- yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_dc4cacc08359_key -iv $encrypted_dc4cacc08359_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
